# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
COPY bun.lockb* ./

# Use bun install to install dependencies
RUN bun install --frozen-lockfile

# Copy all project files
COPY . .

# Build the project
RUN bun run build

# Set environment variables for Docker (actual values should be provided at runtime)
ENV YOUTUBE_API_KEY=""
ENV MDB_MCP_CONNECTION_STRING=""

# Command to run the MCP server
CMD ["bun", "run", "dist/index.js"]
